### ISSUE TITLE
FAQ: What's the role/purpose of the kubefledged-operator? Is it required?

### ISSUE THREAD

**Issue by metasim** [senthilrch/kube-fledged#119]
This is probably a n00b question, but if the `kubefledged-controller` and `kubefledged-webhook-server` cover the primary capabilities, what does `kubefledged-operator` do?

**Comment by senthilrch** [comment]
Hi @jpuskar: Please find below some thoughts on which method would be more suitable for specific use cases:-

1) Deploy using YAML manifests: This is the simplest and easiest method of deploying kube-fledged. This is also the most kubernetes-native of all the three supported methods. And also the most flexible method since it offers plain old yaml manifests that could be easily customized and modified for your needs. No need for users to learn helm or operator. The Yaml manifests (and the helm chart) will be beneficial in a gitops based deployment model as well.

2) Deploy using Helm charts: If you are already packaging and deploying applications to your cluster using helm charts, then this is the most suitable option since I assume you already having the CICD pipelining and tooling in place to consume helm charts. This will also suit environments where GitOps base deployment model is used (provided the GitOps provider supports helm charts, most providers do support). If you want to distribute kube-fledged from a central helm repo, then this will suit such use case.

3) Deploy using Helm operator: If you can consume kube-fledged using either of the above methods, then no need to look at this option at all. Under the hood, the operator uses the same helm chart used in the above option. Certain kubernetes distributions like Openshift provide first-class citizen support for Operators over other deployment options. Not having an operator based deployment option could sometimes become a deal breaker for such environments. The operator facilitates declarative helm releases over imperative helm commands. The operator shields the user from how helm works etc..But if you are comfortable using YAML manifests or Helm, it is preferred to use those options instead of Helm operator.

**Comment by metasim** [comment]
@senthilrch  This is the best, concise writeup I've read on the topic! You should consider writing a Medium article on the subject! :-)

FWIW, we deploy as much of our system as possible as native manifests processed through Kustomize. Almost every time we rely on a Helm chart there ends up being some Pod/Service/Deployment property we need to tweak that's not exposed by the Helm chart. Despite its sometimes verbosity, Kustomize almost always allows us to get what we want, and really appreciate when projects publish vanilla manifests. 

Until coming upon your project I thought the only "Helm Operator" was the deprecated Tiller, so it was helpful to understand the Openshift perspective and how there's still an ecosystem for that approach.
